Feature/review recommendation algorithm1
vitorpereiraa/acme pull request #10
Opened 2023-10-29 18:03 UTC by vitorpereiraa

* added review recommendation algorithm1
* Closes #5 
*

2023-10-30 19:13 UTC, joaonogueira01 approved these changes

2023-10-30 20:10 UTC, joaonogueira01 requested changes

2023-10-30 20:10 UTC, joaonogueira01 commented on src/main/java/com/isep/acme/services/ReviewServiceImpl.java
> +        final List<Review> reviews = repository.findAll();
Precisas de obter todas as reviews? Não consegues filtrar na base de dados?

2023-11-02 22:00 UTC, vitorpereiraa commented on src/main/java/com/isep/acme/services/ReviewServiceImpl.java
> +        final List<Review> reviews = repository.findAll();
This was discussed offline, and we decided to prioritize solving architectural concerns over feature performance.

2023-11-02 22:01 UTC, merged